# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rps2359/SANA_FE_senior/SANA-FE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rps2359/SANA_FE_senior/SANA-FE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rps2359/SANA_FE_senior/SANA-FE/CMakeFiles /home/rps2359/SANA_FE_senior/SANA-FE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rps2359/SANA_FE_senior/SANA-FE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simcpp

# Build rule for target.
simcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simcpp
.PHONY : simcpp

# fast build rule for target.
simcpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/build
.PHONY : simcpp/fast

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

arch.o: arch.cpp.o
.PHONY : arch.o

# target to build an object file
arch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/arch.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/arch.cpp.o
.PHONY : arch.cpp.o

arch.i: arch.cpp.i
.PHONY : arch.i

# target to preprocess a source file
arch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/arch.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/arch.cpp.i
.PHONY : arch.cpp.i

arch.s: arch.cpp.s
.PHONY : arch.s

# target to generate assembly for a file
arch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/arch.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/arch.cpp.s
.PHONY : arch.cpp.s

command.o: command.cpp.o
.PHONY : command.o

# target to build an object file
command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/command.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/command.cpp.o
.PHONY : command.cpp.o

command.i: command.cpp.i
.PHONY : command.i

# target to preprocess a source file
command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/command.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/command.cpp.i
.PHONY : command.cpp.i

command.s: command.cpp.s
.PHONY : command.s

# target to generate assembly for a file
command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/command.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/command.cpp.s
.PHONY : command.cpp.s

description.o: description.cpp.o
.PHONY : description.o

# target to build an object file
description.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/description.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/description.cpp.o
.PHONY : description.cpp.o

description.i: description.cpp.i
.PHONY : description.i

# target to preprocess a source file
description.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/description.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/description.cpp.i
.PHONY : description.cpp.i

description.s: description.cpp.s
.PHONY : description.s

# target to generate assembly for a file
description.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/description.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/description.cpp.s
.PHONY : description.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/main.cpp.s
.PHONY : main.cpp.s

module.o: module.cpp.o
.PHONY : module.o

# target to build an object file
module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/module.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/module.cpp.o
.PHONY : module.cpp.o

module.i: module.cpp.i
.PHONY : module.i

# target to preprocess a source file
module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/module.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/module.cpp.i
.PHONY : module.cpp.i

module.s: module.cpp.s
.PHONY : module.s

# target to generate assembly for a file
module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/module.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/module.cpp.s
.PHONY : module.cpp.s

network.o: network.cpp.o
.PHONY : network.o

# target to build an object file
network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/network.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/network.cpp.o
.PHONY : network.cpp.o

network.i: network.cpp.i
.PHONY : network.i

# target to preprocess a source file
network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/network.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/network.cpp.i
.PHONY : network.cpp.i

network.s: network.cpp.s
.PHONY : network.s

# target to generate assembly for a file
network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/network.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/network.cpp.s
.PHONY : network.cpp.s

plugins.o: plugins.cpp.o
.PHONY : plugins.o

# target to build an object file
plugins.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/plugins.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/plugins.cpp.o
.PHONY : plugins.cpp.o

plugins.i: plugins.cpp.i
.PHONY : plugins.i

# target to preprocess a source file
plugins.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/plugins.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/plugins.cpp.i
.PHONY : plugins.cpp.i

plugins.s: plugins.cpp.s
.PHONY : plugins.s

# target to generate assembly for a file
plugins.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/plugins.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/plugins.cpp.s
.PHONY : plugins.cpp.s

sim.o: sim.cpp.o
.PHONY : sim.o

# target to build an object file
sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/sim.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cpp.o
.PHONY : sim.cpp.o

sim.i: sim.cpp.i
.PHONY : sim.i

# target to preprocess a source file
sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/sim.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cpp.i
.PHONY : sim.cpp.i

sim.s: sim.cpp.s
.PHONY : sim.s

# target to generate assembly for a file
sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simcpp.dir/build.make CMakeFiles/simcpp.dir/sim.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cpp.s
.PHONY : sim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sim"
	@echo "... simcpp"
	@echo "... arch.o"
	@echo "... arch.i"
	@echo "... arch.s"
	@echo "... command.o"
	@echo "... command.i"
	@echo "... command.s"
	@echo "... description.o"
	@echo "... description.i"
	@echo "... description.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... module.o"
	@echo "... module.i"
	@echo "... module.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... plugins.o"
	@echo "... plugins.i"
	@echo "... plugins.s"
	@echo "... sim.o"
	@echo "... sim.i"
	@echo "... sim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

